### ISSUE TITLE
Feature request: retrieve current node HTML and currently applied CSS classes

### ISSUE THREAD

**Issue by zersiax** [ajborka/nvda_developer_toolkit#5]
I have two somewhat related feature requests from using this addon in the field as a fulltime developer, that i think would mesh well with the addon's overall philosophy.

When a sighted developer wants to inspect an element they mouse over it and right-click. THis can at times be problematic for screen reader users, an overlay might be in the way or the content you're on hasn't scrolled into view visually so you can't easily do a simulated right-mouseclick on the element. For sr-only elements this is pretty much impossible to do instantly as well. so I would propose two new gestures:

- Ideally I would love this to be possible just from regular browse mode but I can see how that would be difficult to do, so I would love a gesture at reads the current node's HTML, copying it to the clipboard with a subsequent press for if you want to see it more detailedly.
- Second, a gesture that retrieves the CSS classes currently on a node, including parent node ones, and either lists those classes or lists those classes'  contents somehow. The inspector panel of the browser can do this already, but Chrome's is pretty inaccessible and Firefox is only marginally better. Getting to this info quickly is really important to diagnose visual inconsistencies.

WOuld love to hear how feasible this is :-)

**Comment by ajborka** [comment]
Hi,

To clarify your requests, you want DTK to (1) display all of the CSS classes or CSS classes' contents of a node, and (2) Display/speak the inner HTML of the focused node?
DTK already performs item 1 above. Just press the letter 'a' when DTK features are enabled. As for item 2, it should be fairly routine to add a feature to read inner HTML of a node.
On feature request 1, please respond to the following to clarify the CSS classes feature:
* How many parents in the ancestor tree do you want to get CSS classes from?
* Should this ancestor tree of classes have a single gesture, or is it the web developer's responsibility to ensure he/she has all of the CSS classes of interest?
* It is impossible to render the CSS class' contents from NVDA's API because it is not important to a screen reader what CSS is used to generate the layout. Only the rendered output is important. So, is it OK to only list the classes?

I don't know the timetable for these features, but I will put them in the feature requests list.

**Comment by ajborka** [comment]
@zersiax , obtaining the inner HTML of the control within the NVDA context is impossible. To do this, I need to obtain it outside of the NVDA context, then bring it inside the NVDA context, which presents a security concern for most users.
